### PR TITLE
Adding Gkeyll presentation

### PR DESCRIPTION
**Pull request by JunoRavin**
and corresponding input files for different ways of running Gkeyll simulations.

### CODE REVIEW

**Comment by namurphy** [comment]
@JunoRavin — Should we add lua and a C compiler to the binder environment too?

**Comment by namurphy** [comment]
And here's a link to test this branch: [Binder](https://mybinder.org/v2/gh/JunoRavin/hack-week-2021/HEAD)

**Comment by JunoRavin** [comment]
A C compiler would actually be very cool, as then perhaps one could build and run gkylzero within the binder environment. I apologize; I could have spent more time trying to figure out how to run everything through the binder environment but I ended up just putting things together outside of it as examples of what I'm going to show today.

**Comment by namurphy** [comment]
No worries about that!  I mergeed this and will follow up with adding a gcc compiler, which I think we can do with conda.

**Pull request merged**
